connection:
  driver:   "%database_driver%"
  host:     "%database_host%"
  port:     "%database_port%"
  dbname:   "%database_dbname%"
  schema:   "%database_schema%"
  user:     "%database_user%"
  password:     "%database_password%"

orm:
  entity_dir: Entity
